[package]
name = "edge-book"
description = "Limit order book, matching engine and automated market makers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
edge-core = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
